apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parts
  template:
    metadata:
      labels:
        app: parts
    spec:
      containers:
        - name: parts
          image: konsta2106/parts
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://parts-mongo-srv:27017/parts'
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: parts
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          # imagePullPolicy: Never
          resources:
            limits:
              memory: "700Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata: 
  name: parts-srv
spec:
  selector:
    app: parts
  ports:
    - name: parts
      protocol: TCP
      port: 3000
      targetPort: 3000